[tox]
envlist = py3,flake8,black,lint,ruff,bandit,docs
output_dir={env:SPHINX_OUTPUT_DIR:{toxworkdir}/_build}
isolated_build = True
toxworkdir = {env:TOXWORKDIR:/tmp/tox}

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest \
        --cov=dlt \
        --cov-branch \
        --cov-report=html \
        --cov-report=term-missing \
        {posargs:tests}

[pytest]
filterwarnings =
    error


[testenv:flake8]
basepython = python3
skip_install = true
deps =
    flake8
commands =
    flake8  --format=pylint --output-file=flake8.txt --max-line-length=119

[testenv:ruff]
basepython = python3
skip_install = true
deps =
    ruff==0.4.1
    mypy
commands =
    ruff check ./dlt ./tests

[testenv:black]
skip_install = True
skipsdist = True
deps =
    black
commands =
    black -l 119 --check --diff .

[testenv:lint]
basepython = python3
skip_install = true
deps =
    click
    pylint==3.2.7
commands =
    pylint . --output-format=json:pylint.json,colorized

[testenv:bandit]
basepython = python3
skip_install = true
deps =
    pbr
    bandit[toml]
commands =
    bandit -c pyproject.toml -r . -f json -o bandit.json --exit-zero

[testenv:dev]
basepython = python3
passenv = SOURCE_DATE_EPOCH
skip_install = True
skipsdist = True
deps =
    build
    twine
    wheel
commands =
    python -m build
    twine upload -r software-factory-pypi-dev dist/*

[testenv:release]
basepython = python3
passenv = SOURCE_DATE_EPOCH
skip_install = True
skipsdist = True
deps =
    build
    twine
    wheel
commands =
    python -m build
    twine upload -r software-factory-pypi dist/*

[testenv:docs]
basepython = python3
skip_install = true
deps =
    -rdocs/requirements-docs.txt
commands =
    sphinx-build -b html -d {envtmpdir}/doctrees docs {toxworkdir}/docs_out

